project:
  name: Chelsey Hockett
  description: ''
  tools: []
  current_focus: ''
  needs: []
  links:
    docs: ''
    staging: ''
    production: ''
  team:
    lead: davidwhitenyc
    contributors:
    - pauldingus
  campaign:
    candidate: Chelsey Hockett
    office: Texas US House District 5
  auto_refresh: true
